version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  server:
    build: ./todolist.core
    command: python ./todolist.core/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  #client:
  #  build: ./todolist.web
  #  ports:
  #    - "8001:80"